/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ClasesBase.Consulta;
import ClasesBase.MultiLineCellRenderer;
import ClasesBase.Paciente;
import DAO.*;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

public class HistoriaClinica extends javax.swing.JFrame {

    private Principal antecesor;
    private ABMPacienteCompleto pacienteInterfaz;
    private DAOPaciente daoPaciente;
    private DAOConsulta daoConsulta;
    private LinkedList<Consulta> consultasDeTabla;
    private DAOAntecedentesFamiliares daoAntecFam;
    private DAOAntecedentesGinecologicos daoAntecGinec;
    private DAOAntecedentesGenerales daoAntecGen;
    private ABMConsultaCompleta consultaCompleta;
    private DefaultTableModel dtmConsultas;
    private AntecFamiliares antecedentesFamiliares;
    private AntecGenerales antecedentesGenerales;
    private AntecGinecologicos antecedentesGinecologicos;
    private Paciente paciente;
    private boolean AntecFamModificado;
    private boolean AntecGenModificado;
    private boolean AntecGinecModificado;
     
    /**
     * Creates new form HistoriaClinica
     */
    public HistoriaClinica(Component parent, Paciente p) {
        initComponents();
        AntecFamModificado = false;
        AntecGenModificado = false;
        AntecGinecModificado = false;
        daoPaciente = new DAOPaciente();
        daoConsulta = new DAOConsulta();
        daoAntecFam = new DAOAntecedentesFamiliares();
        daoAntecGen = new DAOAntecedentesGenerales();
        daoAntecGinec = new DAOAntecedentesGinecologicos();
        this.paciente = p;
        this.btnModificarPaciente.grabFocus();
        this.btnVerConsulta.setEnabled(false);
        llenarCampos(paciente,0);
        tblConsultas.getColumn("Fecha").setResizable(false);
        tblConsultas.getColumn("Fecha").setMaxWidth(65);
        tblConsultas.getColumn("Motivo").setResizable(false);
        tblConsultas.getColumn("Diagnóstico").setResizable(false);
        tblConsultas.getColumn("Tipo de Consulta").setResizable(false);
        llenarTabla(paciente.getDni());
        this.setLocationRelativeTo(parent);
        
        antecesor = (Principal) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNuevaConsulta = new javax.swing.JPanel();
        btnNuevaCompleta = new javax.swing.JButton();
        btnNuevaGinecologica = new javax.swing.JButton();
        btnNuevaObstetrica = new javax.swing.JButton();
        pnlBotones = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        pnlConsultas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        btnVerConsulta = new javax.swing.JButton();
        pnlDatosPersonales = new javax.swing.JPanel();
        lblstaticDni = new javax.swing.JLabel();
        lblstaticNumAfiliado = new javax.swing.JLabel();
        lblstaticObraSocial = new javax.swing.JLabel();
        lblstaticFechaNacimiento = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblNumeroAfiliado = new javax.swing.JLabel();
        lblObraSocial = new javax.swing.JLabel();
        pnlAntecedentes = new javax.swing.JPanel();
        btnGenerales = new javax.swing.JButton();
        btnGinecologicos = new javax.swing.JButton();
        btnFamiliares = new javax.swing.JButton();
        lblstaticSangre = new javax.swing.JLabel();
        lblSangre = new javax.swing.JLabel();
        btnModificarPaciente = new javax.swing.JButton();
        lblTelefono = new javax.swing.JLabel();
        lblstaticTelefono = new javax.swing.JLabel();
        pnlFecha1 = new javax.swing.JPanel();
        lblNombrePaciente = new javax.swing.JLabel();
        lblstaticNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historia Clínica");
        setIconImage(getIconImage());
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 723, 598));
        setMinimumSize(new java.awt.Dimension(723, 530));
        setPreferredSize(new java.awt.Dimension(723, 530));
        setResizable(false);

        pnlNuevaConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Nueva Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N

        btnNuevaCompleta.setText("Completa");
        btnNuevaCompleta.setNextFocusableComponent(btnNuevaGinecologica);
        btnNuevaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCompletaActionPerformed(evt);
            }
        });

        btnNuevaGinecologica.setText("Ginecológica");
        btnNuevaGinecologica.setNextFocusableComponent(btnNuevaObstetrica);
        btnNuevaGinecologica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaGinecologicaActionPerformed(evt);
            }
        });

        btnNuevaObstetrica.setText("Obstétrica");
        btnNuevaObstetrica.setNextFocusableComponent(btnVolver);
        btnNuevaObstetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaObstetricaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNuevaConsultaLayout = new javax.swing.GroupLayout(pnlNuevaConsulta);
        pnlNuevaConsulta.setLayout(pnlNuevaConsultaLayout);
        pnlNuevaConsultaLayout.setHorizontalGroup(
            pnlNuevaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevaConsultaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnNuevaCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevaGinecologica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevaObstetrica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNuevaConsultaLayout.setVerticalGroup(
            pnlNuevaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevaConsultaLayout.createSequentialGroup()
                .addGroup(pnlNuevaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevaCompleta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevaObstetrica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNuevaGinecologica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 51, 102));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home_enabled.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addGap(0, 126, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        pnlConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Consultas Anteriores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N

        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Motivo", "Diagnóstico", "Tipo de Consulta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblConsultas);

        btnVerConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerConsulta.setForeground(new java.awt.Color(0, 51, 102));
        btnVerConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver_enabled.png"))); // NOI18N
        btnVerConsulta.setText("Ver");
        btnVerConsulta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVerConsulta.setNextFocusableComponent(btnNuevaCompleta);
        btnVerConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerConsultaMouseExited(evt);
            }
        });
        btnVerConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addComponent(btnVerConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Datos del Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 51, 102))); // NOI18N

        lblstaticDni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstaticDni.setText("Nro. Documento:");

        lblstaticNumAfiliado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstaticNumAfiliado.setText("Nro. Afiliado:");

        lblstaticObraSocial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstaticObraSocial.setText("Obra Social:");

        lblstaticFechaNacimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstaticFechaNacimiento.setText("Fecha de Nacimiento:");

        lblDni.setText("35953232");

        lblFechaNacimiento.setText("21/03/1991");

        lblNumeroAfiliado.setText("3-4534543-2");

        lblObraSocial.setText("OSPAC");

        pnlAntecedentes.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Antecedentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        btnGenerales.setText("Generales");
        btnGenerales.setNextFocusableComponent(btnGinecologicos);
        btnGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralesActionPerformed(evt);
            }
        });

        btnGinecologicos.setText("Ginecológicos");
        btnGinecologicos.setNextFocusableComponent(btnFamiliares);
        btnGinecologicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGinecologicosActionPerformed(evt);
            }
        });

        btnFamiliares.setText("Familiares");
        btnFamiliares.setNextFocusableComponent(btnVerConsulta);
        btnFamiliares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiliaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAntecedentesLayout = new javax.swing.GroupLayout(pnlAntecedentes);
        pnlAntecedentes.setLayout(pnlAntecedentesLayout);
        pnlAntecedentesLayout.setHorizontalGroup(
            pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGinecologicos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFamiliares, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAntecedentesLayout.setVerticalGroup(
            pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerales)
                    .addComponent(btnGinecologicos)
                    .addComponent(btnFamiliares))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        lblstaticSangre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstaticSangre.setText("Sangre:");

        lblSangre.setText("0 -");

        btnModificarPaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificarPaciente.setForeground(new java.awt.Color(0, 51, 102));
        btnModificarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_enabled.png"))); // NOI18N
        btnModificarPaciente.setText("Modificar");
        btnModificarPaciente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarPacienteMouseExited(evt);
            }
        });
        btnModificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPacienteActionPerformed(evt);
            }
        });

        lblTelefono.setText("423654");

        lblstaticTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstaticTelefono.setText("Teléfono:");

        pnlFecha1.setBackground(new java.awt.Color(228, 228, 241));
        pnlFecha1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255), null));

        lblNombrePaciente.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblNombrePaciente.setForeground(new java.awt.Color(0, 51, 102));
        lblNombrePaciente.setText("Lopez, Juan Carlos");

        lblstaticNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstaticNombre.setText("Apellido y Nombre:");

        javax.swing.GroupLayout pnlFecha1Layout = new javax.swing.GroupLayout(pnlFecha1);
        pnlFecha1.setLayout(pnlFecha1Layout);
        pnlFecha1Layout.setHorizontalGroup(
            pnlFecha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFecha1Layout.createSequentialGroup()
                .addComponent(lblstaticNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFecha1Layout.setVerticalGroup(
            pnlFecha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFecha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addComponent(lblstaticNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosPersonalesLayout = new javax.swing.GroupLayout(pnlDatosPersonales);
        pnlDatosPersonales.setLayout(pnlDatosPersonalesLayout);
        pnlDatosPersonalesLayout.setHorizontalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstaticFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblstaticDni, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblstaticSangre)
                            .addComponent(lblstaticTelefono))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblstaticObraSocial))
                            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(lblSangre)
                                .addGap(119, 119, 119)
                                .addComponent(lblstaticNumAfiliado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroAfiliado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(lblObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))))
                    .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(btnModificarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlFecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDatosPersonalesLayout.setVerticalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addComponent(pnlFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblstaticFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTelefono)
                                .addComponent(lblObraSocial)
                                .addComponent(lblstaticObraSocial))
                            .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFechaNacimiento)
                                .addComponent(lblstaticTelefono)))
                        .addGap(1, 1, 1)))
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSangre)
                        .addComponent(lblstaticSangre))
                    .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblstaticDni)
                            .addComponent(lblDni)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroAfiliado)
                        .addComponent(lblstaticNumAfiliado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(pnlAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarPaciente)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlNuevaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlNuevaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCompletaActionPerformed
    consultaCompleta = new ABMConsultaCompleta(this,true,2,paciente.getDni());
    consultaCompleta.setVisible(true);
    }//GEN-LAST:event_btnNuevaCompletaActionPerformed

    private void btnNuevaGinecologicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaGinecologicaActionPerformed
    consultaCompleta = new ABMConsultaCompleta(this, true,1,paciente.getDni());
    consultaCompleta.setVisible(true);
    }//GEN-LAST:event_btnNuevaGinecologicaActionPerformed

    private void btnNuevaObstetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaObstetricaActionPerformed
    consultaCompleta = new ABMConsultaCompleta(this, true,0,paciente.getDni());
    consultaCompleta.setVisible(true);
    }//GEN-LAST:event_btnNuevaObstetricaActionPerformed

    private void btnGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralesActionPerformed
       if(!AntecGenModificado)
       {
            paciente.setAntecGen(daoAntecGen.getAntecedenteGeneral(paciente.getDni()));
            AntecGenModificado = true;
       }
       antecedentesGenerales = new AntecGenerales(this,true,paciente);
       antecedentesGenerales.setVisible(true);
    }//GEN-LAST:event_btnGeneralesActionPerformed

    private void btnGinecologicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGinecologicosActionPerformed
        if(!AntecGinecModificado)
        {
            paciente.setAntecGinec(daoAntecGinec.getAntecedenteGinecologico(paciente.getDni()));
            AntecGinecModificado = true;
        }
        antecedentesGinecologicos = new AntecGinecologicos(this,true,paciente);
        antecedentesGinecologicos.setVisible(true);
    }//GEN-LAST:event_btnGinecologicosActionPerformed

    private void btnFamiliaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiliaresActionPerformed
       if(!AntecFamModificado)
       {
        paciente.setAntecFam(daoAntecFam.getAntecedenteFamiliar(paciente.getDni()));
        AntecFamModificado = true;
       }
        antecedentesFamiliares = new AntecFamiliares(this,true,paciente);
        antecedentesFamiliares.setVisible(true);
        
    }//GEN-LAST:event_btnFamiliaresActionPerformed

    private void btnVerConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerConsultaActionPerformed
        int j = 0,id = this.tblConsultas.getSelectedRow();
        Consulta c = daoConsulta.getConsultaCompleta(this.consultasDeTabla.get(id).getId(),paciente.getDni());
        if(c.getTipoConsulta().compareTo("Completa") == 0)
             j = 2;
        else if (c.getTipoConsulta().compareTo("Ginecologica") == 0)
            j = 1;
        else if (c.getTipoConsulta().compareTo("Obstetrica") == 0)
            j = 0;
        
        consultaCompleta = new ABMConsultaCompleta(this, true,j,paciente.getDni(),c);
        consultaCompleta.setVisible(true);
    }//GEN-LAST:event_btnVerConsultaActionPerformed

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        this.setearLabels(btnVolver, true);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        this.setearLabels(btnVolver, false);
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        antecesor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnModificarPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarPacienteMouseEntered
        this.setearLabels(btnModificarPaciente, true);
    }//GEN-LAST:event_btnModificarPacienteMouseEntered

    private void btnModificarPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarPacienteMouseExited
        this.setearLabels(btnModificarPaciente, false);
    }//GEN-LAST:event_btnModificarPacienteMouseExited

    private void btnModificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPacienteActionPerformed
        paciente = daoPaciente.getPacienteCompleto(paciente.getDni());
        if(AntecFamModificado == false)
        {
            paciente.setAntecFam(daoAntecFam.getAntecedenteFamiliar(paciente.getDni()));
            AntecFamModificado = true;
        }

        if(AntecGenModificado == false)
        {
            paciente.setAntecGen(daoAntecGen.getAntecedenteGeneral(paciente.getDni()));
            AntecGenModificado = true;
        }

        if(AntecGinecModificado == false)
        {
            paciente.setAntecGinec(daoAntecGinec.getAntecedenteGinecologico(paciente.getDni()));
            AntecGinecModificado = true;
        }
        pacienteInterfaz = new ABMPacienteCompleto(this,true,2,this.paciente);
        pacienteInterfaz.setVisible(true);
    }//GEN-LAST:event_btnModificarPacienteActionPerformed

    private void btnVerConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerConsultaMouseEntered
        this.setearLabels(btnVerConsulta, true);
    }//GEN-LAST:event_btnVerConsultaMouseEntered

    private void btnVerConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerConsultaMouseExited
        this.setearLabels(btnVerConsulta, false);
    }//GEN-LAST:event_btnVerConsultaMouseExited

    private void setearLabels(JButton jbtn, boolean entrada){
        if(jbtn.isEnabled())
            if (entrada) {
                jbtn.setFont(new java.awt.Font("Tahoma", 1, 13));
            }
            else {
                jbtn.setFont(new java.awt.Font("Tahoma", 1, 12));
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFamiliares;
    private javax.swing.JButton btnGenerales;
    private javax.swing.JButton btnGinecologicos;
    private javax.swing.JButton btnModificarPaciente;
    private javax.swing.JButton btnNuevaCompleta;
    private javax.swing.JButton btnNuevaGinecologica;
    private javax.swing.JButton btnNuevaObstetrica;
    private javax.swing.JButton btnVerConsulta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JLabel lblNumeroAfiliado;
    private javax.swing.JLabel lblObraSocial;
    private javax.swing.JLabel lblSangre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblstaticDni;
    private javax.swing.JLabel lblstaticFechaNacimiento;
    private javax.swing.JLabel lblstaticNombre;
    private javax.swing.JLabel lblstaticNumAfiliado;
    private javax.swing.JLabel lblstaticObraSocial;
    private javax.swing.JLabel lblstaticSangre;
    private javax.swing.JLabel lblstaticTelefono;
    private javax.swing.JPanel pnlAntecedentes;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JPanel pnlDatosPersonales;
    private javax.swing.JPanel pnlFecha1;
    private javax.swing.JPanel pnlNuevaConsulta;
    private javax.swing.JTable tblConsultas;
    // End of variables declaration//GEN-END:variables
    public Paciente getPaciente() {
        return paciente;
    }

    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    
    /**
     * Metodo utilizado para llenar los campos de la historia clinica de un paciente
     * @param p Paciente
     * @param procedencia 0 Principal, 1 DatosPaciente
     */
    public void llenarCampos(Paciente p,int procedencia) {
        String fecha;
        this.lblNombrePaciente.setText(p.getApellido()+", "+p.getNombre());
        
        if(procedencia == 0)
        {
            fecha = p.getFechaNacimiento().substring(8,10)
                       +"/"+p.getFechaNacimiento().substring(5,7)
                       +"/"+p.getFechaNacimiento().substring(0,4);
            this.lblFechaNacimiento.setText(fecha);
        }
        else
            this.lblFechaNacimiento.setText(p.getFechaNacimiento());
        
        this.lblNumeroAfiliado.setText(p.getNumeroAfiliado());
        this.lblObraSocial.setText(p.getObraSocial().getNombre());
        this.lblTelefono.setText(p.getTelefono());
        this.lblDni.setText(p.getDni()+"");
        
        if(p.getFactor())
            this.lblSangre.setText(p.getGrupoSanguineo()+" +");   
        else
            this.lblSangre.setText(p.getGrupoSanguineo()+" -");
    }
    
    /**
     * Metodo utilizado para cambiar el tamaño de una tabla
     * @param dtmPacientes DefaultTableModel a cambiar
     * @param j tamaño nuevo
     */
    private void cambiarTamañoTabla(DefaultTableModel dtm,int j) {
        dtm.setNumRows(j);
    }
    
    /**
     * Metodo utilizado para llenar la tabla de consultas
     * @param dni dni del paciente al cual le corresponden las consultas
     */
    public void llenarTabla(long dni) {
        Object[] o;
        dtmConsultas = (DefaultTableModel) this.tblConsultas.getModel();
        borrarFilas(dtmConsultas);
        consultasDeTabla = new LinkedList<>();
        consultasDeTabla = daoConsulta.getAllConsultasTabla(dni);
        
        if(consultasDeTabla.size() == 0)
            cambiarTamañoTabla(dtmConsultas,8);
        else
        {
            cambiarTamañoTabla(dtmConsultas,0);
            this.btnVerConsulta.setEnabled(true);
        }
        for (int i = 0; i < consultasDeTabla.size(); i++) {
            o = new Object[4];
            o[0] = consultasDeTabla.get(i).getFecha();
            o[1] = consultasDeTabla.get(i).getMotivo();
            o[2] = consultasDeTabla.get(i).getDiagnostico();
            o[3] = consultasDeTabla.get(i).getTipoConsulta();
            dtmConsultas.addRow(o);
        }
        
        tblConsultas.changeSelection(0, 0, false, false);
        tblConsultas.setDefaultRenderer(String.class, new MultiLineCellRenderer());
    }
    
    
    /**
     * Metodo utilizado para borrar las filas de una tabla
     * @param dtmPacientes DefaultTableModel a partir del cual borrar
     */
    private void borrarFilas(DefaultTableModel dtmPacientes) {
        int j = dtmPacientes.getRowCount();
        for (int i = 0; i < dtmPacientes.getRowCount();) {
            dtmPacientes.removeRow(0);
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/sistema.png"));
        return retValue;
    }
    
}
