/*
 * Interfaz donde se registran y modifican las consultas
 */
package GUI;

import ClasesBase.Consulta;
import ClasesBase.ExamenGinecologico;
import ClasesBase.ExamenObstetrico;
import ClasesBase.MensajesValidaciones;
import DAO.DAOConsulta;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.JButton;

public class ABMConsultaCompleta extends javax.swing.JDialog {
    private HistoriaClinica HC;
    private ExamenGinecologico eGinec;
    private ExamenObstetrico eObste;
    private DAOConsulta daoConsulta;
    private Consulta cons;
    private Calendar c;
    private String dia;
    private String mes;
    private String año;
    private int tipoConsulta,idConsulta;//tipoConsulta = 0 Obstetrica , 1 Ginecologica y 2 Completa
    private long dni;
    private boolean procedencia;//true si proviene de "ver" una consulta, false si es nueva consulta.
    
    /**
     * Creates new form ABMConsultaCompleta
     */
    public ABMConsultaCompleta(java.awt.Frame parent, boolean modal,int tipoConsulta,long dni) {
        super(parent, modal);
        initComponents();
        this.txtaMotivo.grabFocus();
        eGinec = new ExamenGinecologico();
        eObste = new ExamenObstetrico();
        daoConsulta = new DAOConsulta();
        this.lblIMC.setText("");
        this.procedencia = false;
        HC = (HistoriaClinica)parent;
        this.dni = dni;
        this.tipoConsulta = tipoConsulta;
        c = Calendar.getInstance();
        dia = c.get(Calendar.DAY_OF_MONTH) +"";
        mes = c.get(Calendar.MONTH)+1+"";
        año = c.get(Calendar.YEAR)+"";
        this.lblFecha.setText(dia+"/"+mes+"/"+año);
        if(tipoConsulta != 2)
        {
            tpaneExamenes.remove(tipoConsulta);
        }
        if(tipoConsulta == 2)
        {
            this.tpaneExamenes.setSelectedComponent(this.pnlGinecologico);
            this.txtfDiagnostico.setNextFocusableComponent(this.txtaMamas);
            this.txtaPapYColpo.setNextFocusableComponent(this.txtfTalla);
        }
        else if(tipoConsulta == 1)
        {
            this.txtaPapYColpo.setNextFocusableComponent(this.btnGuardar);
        }
        else if(tipoConsulta == 0)
        {
            this.tpaneExamenes.setSelectedComponent(this.pnlObstetrico);
            this.txtfDiagnostico.setNextFocusableComponent(this.txtfPeso);
        }
        this.setLocationRelativeTo(parent);
        this.setearEstadoCajas(false, tipoConsulta);
    }
    
    /**
     * Creates new form ABMConsultaCompleta
     */
    public ABMConsultaCompleta(java.awt.Frame parent, boolean modal,int tipoConsulta,long dni,Consulta con) {
        super(parent, modal);
        initComponents();
        this.txtaMotivo.grabFocus();
        eGinec = new ExamenGinecologico();
        eObste = new ExamenObstetrico();
        daoConsulta = new DAOConsulta();
        HC = (HistoriaClinica)parent;
        this.procedencia = true;
        this.dni = dni;
        this.tipoConsulta = tipoConsulta;
        this.lblIMC.setText("");
        idConsulta = con.getId();
        c = Calendar.getInstance();
        dia = c.get(Calendar.DAY_OF_MONTH) +"";
        mes = c.get(Calendar.MONTH)+1+"";
        año = c.get(Calendar.YEAR)+"";
        this.lblFecha.setText(dia+"/"+mes+"/"+año);
        llenarCajas(con);
        cambiarBotones(false);
        setearEstadoCajas(false,tipoConsulta);
        if(tipoConsulta != 2)
        {
            tpaneExamenes.remove(tipoConsulta);
        }
        if(tipoConsulta == 2)
        {
            this.tpaneExamenes.setSelectedComponent(this.pnlGinecologico);
            this.txtfDiagnostico.setNextFocusableComponent(this.txtaMamas);
            this.txtaPapYColpo.setNextFocusableComponent(this.txtfTalla);
        }
        else if(tipoConsulta == 1)
        {
            this.txtaPapYColpo.setNextFocusableComponent(this.btnGuardar);
        }
        else if(tipoConsulta == 0)
        {
            this.tpaneExamenes.setSelectedComponent(this.pnlObstetrico);
            this.txtfDiagnostico.setNextFocusableComponent(this.txtfPeso);
        }
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpMAF = new javax.swing.ButtonGroup();
        tpaneExamenes = new javax.swing.JTabbedPane();
        pnlObstetrico = new javax.swing.JPanel();
        rbtnMafNo = new javax.swing.JRadioButton();
        rbtnMafSi = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaObstetObservaciones = new javax.swing.JTextArea();
        lblstaticObstetricoObserv = new javax.swing.JLabel();
        lblstaticAU = new javax.swing.JLabel();
        lblstaticTalla = new javax.swing.JLabel();
        lblstaticPeso = new javax.swing.JLabel();
        lblstaticLCF = new javax.swing.JLabel();
        lblstaticMAF = new javax.swing.JLabel();
        txtfLCF = new javax.swing.JTextField();
        txtfPeso = new javax.swing.JTextField();
        txtfTalla = new javax.swing.JTextField();
        lblstaticPA = new javax.swing.JLabel();
        txtfPresionArterial = new javax.swing.JTextField();
        txtfAlturaUterina = new javax.swing.JTextField();
        lblstaticUnidadPA = new javax.swing.JLabel();
        lblstaticUnidadAU = new javax.swing.JLabel();
        lblstaticUnidadTalla = new javax.swing.JLabel();
        lblstaticUnidadPeso = new javax.swing.JLabel();
        lblstaticUnidadLCF = new javax.swing.JLabel();
        lblstaticIMC = new javax.swing.JLabel();
        lblIMC = new javax.swing.JLabel();
        pnlGinecologico = new javax.swing.JPanel();
        lblstaticMamas = new javax.swing.JLabel();
        lblstaticGenito = new javax.swing.JLabel();
        lblstaticBethesda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaMamas = new javax.swing.JTextArea();
        cmbBethesda = new javax.swing.JComboBox();
        lblstaticPap = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaPapYColpo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtaGenitoUrinario = new javax.swing.JTextArea();
        pnlMotivo = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtaMotivo = new javax.swing.JTextArea();
        pnlFecha = new javax.swing.JPanel();
        lblstaticFecha = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        pnlTratamiento = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtaTratamiento = new javax.swing.JTextArea();
        pnlEstudiosComplementarios = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtaEstudiosComple = new javax.swing.JTextArea();
        pnlObservaciones = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtaObservaciones = new javax.swing.JTextArea();
        pnlObservaciones1 = new javax.swing.JPanel();
        txtfDiagnostico = new javax.swing.JTextField();
        pnlBotones1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnVolver1 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Completa");
        setResizable(false);

        tpaneExamenes.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Exámenes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N

        btngrpMAF.add(rbtnMafNo);
        rbtnMafNo.setText("NO");
        rbtnMafNo.setNextFocusableComponent(txtaObstetObservaciones);
        rbtnMafNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rbtnMafNoKeyTyped(evt);
            }
        });

        btngrpMAF.add(rbtnMafSi);
        rbtnMafSi.setText("SI");
        rbtnMafSi.setNextFocusableComponent(rbtnMafNo);
        rbtnMafSi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rbtnMafSiKeyTyped(evt);
            }
        });

        txtaObstetObservaciones.setColumns(20);
        txtaObstetObservaciones.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtaObstetObservaciones.setRows(5);
        txtaObstetObservaciones.setTabSize(0);
        txtaObstetObservaciones.setWrapStyleWord(true);
        txtaObstetObservaciones.setNextFocusableComponent(btnGuardar);
        txtaObstetObservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaObstetObservacionesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtaObstetObservaciones);

        lblstaticObstetricoObserv.setText("Observaciones:");

        lblstaticAU.setText("Altura Uterina:");

        lblstaticTalla.setText("Talla:");

        lblstaticPeso.setText("Peso:");

        lblstaticLCF.setText("LCF:");

        lblstaticMAF.setText("MAF:");

        txtfLCF.setNextFocusableComponent(rbtnMafSi);
        txtfLCF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfLCFKeyTyped(evt);
            }
        });

        txtfPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtfPeso.setHighlighter(null);
        txtfPeso.setNextFocusableComponent(txtfAlturaUterina);
        txtfPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfPesoKeyTyped(evt);
            }
        });

        txtfTalla.setHighlighter(null);
        txtfTalla.setNextFocusableComponent(txtfPeso);
        txtfTalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfTallaKeyTyped(evt);
            }
        });

        lblstaticPA.setText("Presión Arterial:");

        txtfPresionArterial.setNextFocusableComponent(txtfLCF);
        txtfPresionArterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfPresionArterialKeyTyped(evt);
            }
        });

        txtfAlturaUterina.setNextFocusableComponent(txtfPresionArterial);
        txtfAlturaUterina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfAlturaUterinaKeyTyped(evt);
            }
        });

        lblstaticUnidadPA.setText("mm/hg");

        lblstaticUnidadAU.setText("cm");

        lblstaticUnidadTalla.setText("m");

        lblstaticUnidadPeso.setText("Kg");

        lblstaticUnidadLCF.setText("lpm");

        lblstaticIMC.setText("IMC:");

        lblIMC.setText("Aca va el imc");

        javax.swing.GroupLayout pnlObstetricoLayout = new javax.swing.GroupLayout(pnlObstetrico);
        pnlObstetrico.setLayout(pnlObstetricoLayout);
        pnlObstetricoLayout.setHorizontalGroup(
            pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObstetricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlObstetricoLayout.createSequentialGroup()
                        .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlObstetricoLayout.createSequentialGroup()
                                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblstaticTalla)
                                    .addComponent(lblstaticPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblstaticIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtfTalla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(txtfPeso)
                                    .addComponent(lblIMC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblstaticUnidadTalla)
                                    .addComponent(lblstaticUnidadPeso))
                                .addGap(32, 32, 32)
                                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlObstetricoLayout.createSequentialGroup()
                                        .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblstaticPA)
                                            .addComponent(lblstaticMAF)
                                            .addComponent(lblstaticLCF))
                                        .addGap(18, 18, 18))
                                    .addGroup(pnlObstetricoLayout.createSequentialGroup()
                                        .addComponent(lblstaticAU)
                                        .addGap(24, 24, 24)))
                                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfPresionArterial)
                                    .addComponent(txtfLCF)
                                    .addGroup(pnlObstetricoLayout.createSequentialGroup()
                                        .addComponent(rbtnMafSi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnMafNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtfAlturaUterina))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblstaticUnidadPA)
                                    .addComponent(lblstaticUnidadAU)
                                    .addComponent(lblstaticUnidadLCF)))
                            .addComponent(lblstaticObstetricoObserv))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlObstetricoLayout.setVerticalGroup(
            pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObstetricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaticTalla)
                    .addComponent(txtfTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticAU)
                    .addComponent(txtfAlturaUterina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticUnidadAU)
                    .addComponent(lblstaticUnidadTalla))
                .addGap(18, 18, 18)
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaticPeso)
                    .addComponent(txtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticPA)
                    .addComponent(txtfPresionArterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticUnidadPA)
                    .addComponent(lblstaticUnidadPeso))
                .addGap(21, 21, 21)
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaticLCF)
                    .addComponent(txtfLCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticUnidadLCF)
                    .addComponent(lblstaticIMC)
                    .addComponent(lblIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMafSi)
                    .addComponent(rbtnMafNo)
                    .addComponent(lblstaticMAF))
                .addGap(18, 18, 18)
                .addComponent(lblstaticObstetricoObserv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpaneExamenes.addTab("Obstétrico", pnlObstetrico);

        lblstaticMamas.setText("Mamas:");

        lblstaticGenito.setText("Genitourinario:");

        lblstaticBethesda.setText("Bethesda:");

        txtaMamas.setColumns(20);
        txtaMamas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtaMamas.setLineWrap(true);
        txtaMamas.setRows(2);
        txtaMamas.setTabSize(0);
        txtaMamas.setWrapStyleWord(true);
        txtaMamas.setNextFocusableComponent(txtaGenitoUrinario);
        txtaMamas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaMamasKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtaMamas);

        cmbBethesda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II", "III", "IV", "V" }));
        cmbBethesda.setNextFocusableComponent(txtaPapYColpo);
        cmbBethesda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbBethesdaKeyTyped(evt);
            }
        });

        lblstaticPap.setText("Papanicolau y Colposcopia:");

        txtaPapYColpo.setColumns(20);
        txtaPapYColpo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtaPapYColpo.setLineWrap(true);
        txtaPapYColpo.setRows(4);
        txtaPapYColpo.setTabSize(0);
        txtaPapYColpo.setWrapStyleWord(true);
        txtaPapYColpo.setNextFocusableComponent(btnGuardar);
        txtaPapYColpo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaPapYColpoKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtaPapYColpo);

        txtaGenitoUrinario.setColumns(20);
        txtaGenitoUrinario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtaGenitoUrinario.setLineWrap(true);
        txtaGenitoUrinario.setRows(4);
        txtaGenitoUrinario.setTabSize(0);
        txtaGenitoUrinario.setWrapStyleWord(true);
        txtaGenitoUrinario.setNextFocusableComponent(cmbBethesda);
        txtaGenitoUrinario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaGenitoUrinarioKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtaGenitoUrinario);

        javax.swing.GroupLayout pnlGinecologicoLayout = new javax.swing.GroupLayout(pnlGinecologico);
        pnlGinecologico.setLayout(pnlGinecologicoLayout);
        pnlGinecologicoLayout.setHorizontalGroup(
            pnlGinecologicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGinecologicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGinecologicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(lblstaticMamas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblstaticGenito, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlGinecologicoLayout.createSequentialGroup()
                        .addComponent(lblstaticBethesda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBethesda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblstaticPap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGinecologicoLayout.setVerticalGroup(
            pnlGinecologicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGinecologicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblstaticMamas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblstaticGenito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGinecologicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaticBethesda)
                    .addComponent(cmbBethesda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblstaticPap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpaneExamenes.addTab("Ginecológico", pnlGinecologico);

        pnlMotivo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Motivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        pnlMotivo.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        txtaMotivo.setColumns(20);
        txtaMotivo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtaMotivo.setLineWrap(true);
        txtaMotivo.setRows(2);
        txtaMotivo.setTabSize(0);
        txtaMotivo.setWrapStyleWord(true);
        txtaMotivo.setNextFocusableComponent(txtaTratamiento);
        txtaMotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaMotivoKeyTyped(evt);
            }
        });
        jScrollPane9.setViewportView(txtaMotivo);

        javax.swing.GroupLayout pnlMotivoLayout = new javax.swing.GroupLayout(pnlMotivo);
        pnlMotivo.setLayout(pnlMotivoLayout);
        pnlMotivoLayout.setHorizontalGroup(
            pnlMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9)
        );
        pnlMotivoLayout.setVerticalGroup(
            pnlMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        pnlFecha.setBackground(new java.awt.Color(228, 228, 241));
        pnlFecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255), null));

        lblstaticFecha.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblstaticFecha.setForeground(new java.awt.Color(0, 51, 102));
        lblstaticFecha.setText("Fecha:");

        lblFecha.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 51, 102));
        lblFecha.setText("FechaDeHoy");

        javax.swing.GroupLayout pnlFechaLayout = new javax.swing.GroupLayout(pnlFecha);
        pnlFecha.setLayout(pnlFechaLayout);
        pnlFechaLayout.setHorizontalGroup(
            pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechaLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblstaticFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        pnlFechaLayout.setVerticalGroup(
            pnlFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblstaticFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlTratamiento.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Tratamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        pnlTratamiento.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        txtaTratamiento.setColumns(20);
        txtaTratamiento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtaTratamiento.setLineWrap(true);
        txtaTratamiento.setRows(2);
        txtaTratamiento.setTabSize(0);
        txtaTratamiento.setWrapStyleWord(true);
        txtaTratamiento.setNextFocusableComponent(txtaEstudiosComple);
        txtaTratamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaTratamientoKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(txtaTratamiento);

        javax.swing.GroupLayout pnlTratamientoLayout = new javax.swing.GroupLayout(pnlTratamiento);
        pnlTratamiento.setLayout(pnlTratamientoLayout);
        pnlTratamientoLayout.setHorizontalGroup(
            pnlTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );
        pnlTratamientoLayout.setVerticalGroup(
            pnlTratamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlEstudiosComplementarios.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Estudios Complementarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        pnlEstudiosComplementarios.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        txtaEstudiosComple.setColumns(20);
        txtaEstudiosComple.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtaEstudiosComple.setLineWrap(true);
        txtaEstudiosComple.setRows(2);
        txtaEstudiosComple.setTabSize(0);
        txtaEstudiosComple.setWrapStyleWord(true);
        txtaEstudiosComple.setNextFocusableComponent(txtaObservaciones);
        txtaEstudiosComple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaEstudiosCompleKeyTyped(evt);
            }
        });
        jScrollPane10.setViewportView(txtaEstudiosComple);

        javax.swing.GroupLayout pnlEstudiosComplementariosLayout = new javax.swing.GroupLayout(pnlEstudiosComplementarios);
        pnlEstudiosComplementarios.setLayout(pnlEstudiosComplementariosLayout);
        pnlEstudiosComplementariosLayout.setHorizontalGroup(
            pnlEstudiosComplementariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10)
        );
        pnlEstudiosComplementariosLayout.setVerticalGroup(
            pnlEstudiosComplementariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        pnlObservaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Observaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        pnlObservaciones.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        txtaObservaciones.setColumns(20);
        txtaObservaciones.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtaObservaciones.setLineWrap(true);
        txtaObservaciones.setRows(2);
        txtaObservaciones.setTabSize(0);
        txtaObservaciones.setWrapStyleWord(true);
        txtaObservaciones.setNextFocusableComponent(txtfDiagnostico);
        txtaObservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaObservacionesKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(txtaObservaciones);

        javax.swing.GroupLayout pnlObservacionesLayout = new javax.swing.GroupLayout(pnlObservaciones);
        pnlObservaciones.setLayout(pnlObservacionesLayout);
        pnlObservacionesLayout.setHorizontalGroup(
            pnlObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
        );
        pnlObservacionesLayout.setVerticalGroup(
            pnlObservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        pnlObservaciones1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Diagnóstico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 51, 102))); // NOI18N
        pnlObservaciones1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        txtfDiagnostico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtfDiagnostico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfDiagnosticoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlObservaciones1Layout = new javax.swing.GroupLayout(pnlObservaciones1);
        pnlObservaciones1.setLayout(pnlObservaciones1Layout);
        pnlObservaciones1Layout.setHorizontalGroup(
            pnlObservaciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtfDiagnostico)
        );
        pnlObservaciones1Layout.setVerticalGroup(
            pnlObservaciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtfDiagnostico)
        );

        pnlBotones1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 51, 102));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_enabled.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setEnabled(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(0, 51, 102));
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel_enabled.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar1.setEnabled(false);
        btnCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelar1MouseExited(evt);
            }
        });
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnVolver1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(0, 51, 102));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home_enabled.png"))); // NOI18N
        btnVolver1.setText("Volver");
        btnVolver1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolver1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolver1MouseExited(evt);
            }
        });
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 51, 102));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_enabled.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotones1Layout = new javax.swing.GroupLayout(pnlBotones1);
        pnlBotones1.setLayout(pnlBotones1Layout);
        pnlBotones1Layout.setHorizontalGroup(
            pnlBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotones1Layout.createSequentialGroup()
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotones1Layout.setVerticalGroup(
            pnlBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCancelar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGuardar)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTratamiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMotivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEstudiosComplementarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlObservaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlObservaciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tpaneExamenes)
                    .addComponent(pnlBotones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tpaneExamenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(pnlMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(pnlTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEstudiosComplementarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlObservaciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfTallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfTallaKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtfTalla.nextFocus();
        }  
        if(MensajesValidaciones.negarCaracteresFloat(evt, this))
            return;
                float talla,peso;

        String textoTalla=this.txtfTalla.getText();
        if(textoTalla.contains(".") == true && evt.getKeyChar() == KeyEvent.VK_PERIOD)
        {   
            evt.consume();
            return;
        }
        int i = this.txtfTalla.getText().length();
        String textoPeso = this.txtfPeso.getText();
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE || evt.getKeyChar() == KeyEvent.VK_PERIOD ){
            if(i > 1)
                textoTalla = this.txtfTalla.getText().substring(0, this.txtfTalla.getText().length() - 1);
            else if(i == 1)
                textoTalla = this.txtfTalla.getText();
            else if(i == 0){
                this.lblIMC.setText("");   
                return;
            }
        }
        else
        {
        textoTalla += evt.getKeyChar();
        }
        talla = Float.parseFloat(textoTalla);
        if(talla == 0)
        {
            evt.consume();
            return;
        }
        if(!textoPeso.isEmpty())
        {
        peso = Float.parseFloat(textoPeso);
        float resultadoIMC = peso/(talla*talla);
        lblIMC.setText(resultadoIMC+"");
        }        
    }//GEN-LAST:event_txtfTallaKeyTyped

    private void txtfPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPesoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtfPeso.nextFocus();
        }  
        if(MensajesValidaciones.negarCaracteresFloat(evt, this))
            return;
        
        float talla,peso;
        String textoTalla = this.txtfTalla.getText();
        String textoPeso = this.txtfPeso.getText();
        int i = this.txtfPeso.getText().length();
        if(textoPeso.contains(".") == true  && evt.getKeyChar() == KeyEvent.VK_PERIOD)
        {   
            evt.consume();
            return;
        }
        if(i == 0 && evt.getKeyChar() == KeyEvent.VK_0)
        {
            evt.consume();
            return;
        }
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE){
            if(i > 1)
                textoPeso = this.txtfPeso.getText().substring(0, this.txtfPeso.getText().length() - 1);
            else if(i == 1)
                textoPeso = this.txtfPeso.getText();
            else if(i == 0){
                this.lblIMC.setText("");   
                return;
            }
        }
        else
        {
        textoPeso += evt.getKeyChar();
        }
        peso = Float.parseFloat(textoPeso);
        if(peso == 0)
        {
            evt.consume();
            return;
        }
        if(!textoTalla.isEmpty())
        {
        talla = Float.parseFloat(textoTalla);
        float resultadoIMC = peso/(talla*talla);
        lblIMC.setText(resultadoIMC+"");
        }
        else
        {
        lblIMC.setText("");
        }
    }//GEN-LAST:event_txtfPesoKeyTyped

    private void txtfAlturaUterinaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfAlturaUterinaKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtfAlturaUterina.nextFocus();
        }  
        MensajesValidaciones.negarLetras(evt, this);
    }//GEN-LAST:event_txtfAlturaUterinaKeyTyped

    private void txtfPresionArterialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPresionArterialKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtfPresionArterial.nextFocus();
        }  
        MensajesValidaciones.negarLetras(evt, this);
    }//GEN-LAST:event_txtfPresionArterialKeyTyped

    private void txtfLCFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfLCFKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtfPresionArterial.nextFocus();
        }  
        MensajesValidaciones.negarLetras(evt, this);
    }//GEN-LAST:event_txtfLCFKeyTyped

    private void txtaPapYColpoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaPapYColpoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.tpaneExamenes.setSelectedComponent(this.pnlObstetrico);
            this.txtaPapYColpo.nextFocus();
        } 
    }//GEN-LAST:event_txtaPapYColpoKeyTyped

    private void rbtnMafSiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnMafSiKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.rbtnMafSi.nextFocus();
        }  
    }//GEN-LAST:event_rbtnMafSiKeyTyped

    private void rbtnMafNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbtnMafNoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.rbtnMafNo.nextFocus();
        }  
    }//GEN-LAST:event_rbtnMafNoKeyTyped

    private void txtaMotivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaMotivoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {
            this.txtaMotivo.nextFocus();
        }   
    }//GEN-LAST:event_txtaMotivoKeyTyped

    private void txtaTratamientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaTratamientoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtaTratamiento.nextFocus();
        }  
    }//GEN-LAST:event_txtaTratamientoKeyTyped

    private void txtfDiagnosticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfDiagnosticoKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtfDiagnostico.nextFocus();
        } 
    }//GEN-LAST:event_txtfDiagnosticoKeyTyped

    private void txtaEstudiosCompleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaEstudiosCompleKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtaEstudiosComple.nextFocus();
        }  
    }//GEN-LAST:event_txtaEstudiosCompleKeyTyped

    private void txtaObservacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaObservacionesKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtaObservaciones.nextFocus();
        } 
    }//GEN-LAST:event_txtaObservacionesKeyTyped

    private void txtaMamasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaMamasKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtaMamas.nextFocus();
        } 
    }//GEN-LAST:event_txtaMamasKeyTyped

    private void txtaGenitoUrinarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaGenitoUrinarioKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtaGenitoUrinario.nextFocus();
        } 
    }//GEN-LAST:event_txtaGenitoUrinarioKeyTyped

    private void cmbBethesdaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbBethesdaKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.cmbBethesda.nextFocus();
        } 
    }//GEN-LAST:event_cmbBethesdaKeyTyped

    private void txtaObstetObservacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaObstetObservacionesKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_TAB)
        {   
            this.txtaObstetObservaciones.nextFocus();
        }  
    }//GEN-LAST:event_txtaObstetObservacionesKeyTyped

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        this.setearLabels(btnGuardar, true);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        this.setearLabels(btnGuardar, false);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String error = comprobarObligatorias(tipoConsulta);
        if(!error.isEmpty())
        {
            MensajesValidaciones.mostrarError(this,"Debe completar los siguientes datos obligatorios: \n"+error);
            return;
        }   
    
        generarConsultaMedica();

        if(!procedencia)
        {
            if(daoConsulta.RegistrarConsulta(cons, dni,tipoConsulta))
            {
                MensajesValidaciones.mostrarInformacion(this, "Registro Exitoso.");
            }
            else
            {
                MensajesValidaciones.mostrarError(this, "Registro Fallido.");
            }
        }
        else
        {
            if(daoConsulta.actualizarConsulta(cons))
            {
                MensajesValidaciones.mostrarInformacion(this, "Actualización Exitosa.");
                setearEstadoCajas(false, tipoConsulta);
                cambiarBotones(false);
            }
            else
            {
                MensajesValidaciones.mostrarError(this, "Actualización Fallida.");
            }
        }
        HC.llenarTabla(dni);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar1MouseEntered
        this.setearLabels(btnCancelar1, true);
    }//GEN-LAST:event_btnCancelar1MouseEntered

    private void btnCancelar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelar1MouseExited
        this.setearLabels(btnCancelar1, false);
    }//GEN-LAST:event_btnCancelar1MouseExited

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        this.llenarCajas(cons);
        this.setearEstadoCajas(false, tipoConsulta);
        this.btnGuardar.setEnabled(false);
        this.btnModificar.setEnabled(true);
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnVolver1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver1MouseEntered
        this.setearLabels(btnVolver1, true);
    }//GEN-LAST:event_btnVolver1MouseEntered

    private void btnVolver1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver1MouseExited
        this.setearLabels(btnVolver1, false);
    }//GEN-LAST:event_btnVolver1MouseExited

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        this.dispose();
        HC.setVisible(true);
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered
        this.setearLabels(btnModificar, true);
    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
        this.setearLabels(btnModificar, false);
    }//GEN-LAST:event_btnModificarMouseExited

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        cambiarBotones(true);
        setearEstadoCajas(true, tipoConsulta);
        this.btnGuardar.setEnabled(true);
        this.btnModificar.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void setearLabels(JButton jbtn, boolean entrada){
        if(jbtn.isEnabled())
            if (entrada) {
                jbtn.setFont(new java.awt.Font("Tahoma", 1, 13));
            }
            else {
                jbtn.setFont(new java.awt.Font("Tahoma", 1, 12));
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.ButtonGroup btngrpMAF;
    private javax.swing.JComboBox cmbBethesda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblstaticAU;
    private javax.swing.JLabel lblstaticBethesda;
    private javax.swing.JLabel lblstaticFecha;
    private javax.swing.JLabel lblstaticGenito;
    private javax.swing.JLabel lblstaticIMC;
    private javax.swing.JLabel lblstaticLCF;
    private javax.swing.JLabel lblstaticMAF;
    private javax.swing.JLabel lblstaticMamas;
    private javax.swing.JLabel lblstaticObstetricoObserv;
    private javax.swing.JLabel lblstaticPA;
    private javax.swing.JLabel lblstaticPap;
    private javax.swing.JLabel lblstaticPeso;
    private javax.swing.JLabel lblstaticTalla;
    private javax.swing.JLabel lblstaticUnidadAU;
    private javax.swing.JLabel lblstaticUnidadLCF;
    private javax.swing.JLabel lblstaticUnidadPA;
    private javax.swing.JLabel lblstaticUnidadPeso;
    private javax.swing.JLabel lblstaticUnidadTalla;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlBotones1;
    private javax.swing.JPanel pnlEstudiosComplementarios;
    private javax.swing.JPanel pnlFecha;
    private javax.swing.JPanel pnlGinecologico;
    private javax.swing.JPanel pnlMotivo;
    private javax.swing.JPanel pnlMotivo1;
    private javax.swing.JPanel pnlMotivo2;
    private javax.swing.JPanel pnlObservaciones;
    private javax.swing.JPanel pnlObservaciones1;
    private javax.swing.JPanel pnlObstetrico;
    private javax.swing.JPanel pnlTratamiento;
    private javax.swing.JRadioButton rbtnMafNo;
    private javax.swing.JRadioButton rbtnMafSi;
    private javax.swing.JTabbedPane tpaneExamenes;
    private javax.swing.JTextArea txtaEstudiosComple;
    private javax.swing.JTextArea txtaGenitoUrinario;
    private javax.swing.JTextArea txtaMamas;
    private javax.swing.JTextArea txtaMotivo;
    private javax.swing.JTextArea txtaMotivo1;
    private javax.swing.JTextArea txtaMotivo2;
    private javax.swing.JTextArea txtaObservaciones;
    private javax.swing.JTextArea txtaObstetObservaciones;
    private javax.swing.JTextArea txtaPapYColpo;
    private javax.swing.JTextArea txtaTratamiento;
    private javax.swing.JTextField txtfAlturaUterina;
    private javax.swing.JTextField txtfDiagnostico;
    private javax.swing.JTextField txtfLCF;
    private javax.swing.JTextField txtfPeso;
    private javax.swing.JTextField txtfPresionArterial;
    private javax.swing.JTextField txtfTalla;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Metodo utilizado para llenar los datos de una consulta
     * @param c Consulta
     */
    private void llenarCajas(Consulta c) {
        this.lblFecha.setText(c.getFecha());
        this.txtaMotivo.setText(c.getMotivo());
        this.txtaTratamiento.setText(c.getTratamiento());
        this.txtaEstudiosComple.setText(c.getEstudiosComplementarios());
        this.txtaObservaciones.setText(c.getObservaciones());
        this.txtfDiagnostico.setText(c.getDiagnostico());
        if(tipoConsulta == 2 || tipoConsulta == 1)
        {
            this.txtaMamas.setText(c.getExamenGinecologico().getMamas());
            this.txtaGenitoUrinario.setText(c.getExamenGinecologico().getGenitourinario());
            this.txtaPapYColpo.setText(c.getExamenGinecologico().getPapycolposcopia());
            this.cmbBethesda.setSelectedItem(c.getExamenGinecologico().getBethesda());
        }
        if(tipoConsulta == 2 || tipoConsulta == 0)
        {
            this.txtfTalla.setText(c.getExamenObstetrico().getTalla()+"");
            this.txtfPeso.setText(c.getExamenObstetrico().getPeso()+"");
            this.txtfAlturaUterina.setText(c.getExamenObstetrico().getAu()+"");
            this.txtfPresionArterial.setText(c.getExamenObstetrico().getPa()+"");
            this.txtfLCF.setText(c.getExamenObstetrico().getLcf()+"");
            this.txtaObstetObservaciones.setText(c.getExamenObstetrico().getObservaciones()+"");
            if(c.getExamenObstetrico().getMaf())
                this.rbtnMafSi.setSelected(true);
            else
                this.rbtnMafNo.setSelected(true);
            this.lblIMC.setText(c.getExamenObstetrico().getImc()+"");
        }
    }
    
    /**
     * Metodo utilizado para validar el ingreso en las cajas obligatorias
     * @param tipoConsulta tipo de consulta (0 Obstetrica , 1 Ginecologica y 2 Completa)
     */
    private String comprobarObligatorias(int tipoConsulta) {//estudios complementarios y observaciones no son obligatorios
        String incompletas="";
        
        if(this.txtaMotivo.getText().isEmpty())
            incompletas+="Motivo \n";
        
        if(this.txtaTratamiento.getText().isEmpty())
            incompletas+="Tratamiento \n";
        
        if(this.txtfDiagnostico.getText().isEmpty())
            incompletas+="Diagnóstico \n";
        
        if(tipoConsulta == 2 || tipoConsulta == 1)
        {
            if(this.txtaMamas.getText().isEmpty())
                incompletas+="Mamas \n";
        
            if(this.txtaGenitoUrinario.getText().isEmpty())
                incompletas += "Genitourinario \n";
        
            if(this.txtaPapYColpo.getText().isEmpty())
                incompletas += "Papanicolau y Colposcopia \n";
        }
        
        if(tipoConsulta == 2 || tipoConsulta == 0)
        {
            if(this.txtfTalla.getText().isEmpty())
                incompletas+="Talla \n";
            else if (Float.parseFloat(this.txtfTalla.getText()) == 0)
                incompletas+="Talla no puede ser 0 \n";
            
            if(this.txtfPeso.getText().isEmpty())
                incompletas += "Peso \n";
            else if(Integer.parseInt(this.txtfPeso.getText()) == 0)
                incompletas += "Peso no puede ser 0";
            
            if(this.txtfAlturaUterina.getText().isEmpty())
                incompletas += "Altura Uterina \n";
            
            if(this.txtfPresionArterial.getText().isEmpty())
                incompletas += "Presión Arterial \n";
            
            if(this.txtfLCF.getText().isEmpty())
                incompletas += "LCF \n";
            
            if(this.rbtnMafNo.isSelected() == false && this.rbtnMafSi.isSelected() == false)
                incompletas += "MAF";        
        
        }
        return incompletas;

    }
    
    /**
     * Metodo utilizado para generar una consulta
     */
    private void generarConsultaMedica() {
        cons = new Consulta();
        cons.setId(idConsulta);
        cons.setDiagnostico(this.txtfDiagnostico.getText());
        cons.setEstudiosComplementarios(this.txtaEstudiosComple.getText());
        cons.setFecha(this.lblFecha.getText());
        cons.setMotivo(this.txtaMotivo.getText());
        cons.setObservaciones(this.txtaObservaciones.getText());
        switch(tipoConsulta)
        {
            case 0 : cons.setTipoConsulta("Obstetrica");  
                     break;
            case 1 : cons.setTipoConsulta("Ginecologica");
                     break;
            case 2 : cons.setTipoConsulta("Completa");
                     break;
        }
        cons.setTratamiento(this.txtaTratamiento.getText());
        
        generarExamenes();
        
        cons.setExamenGinecologico(eGinec);
        cons.setExamenObstetrico(eObste);
        }

    /**
     * Metodo utilizado para generar los examenes de las consultas
     */
    private void generarExamenes() {
        eGinec = new ExamenGinecologico();
        eObste = new ExamenObstetrico();
        
        if(tipoConsulta == 1 || tipoConsulta == 2){
        eGinec.setBethesda(this.cmbBethesda.getSelectedItem().toString());
        eGinec.setGenitourinario(this.txtaGenitoUrinario.getText());
        eGinec.setMamas(this.txtaMamas.getText());
        eGinec.setPapycolposcopia(this.txtaPapYColpo.getText());
        }
        
        if(tipoConsulta == 0 || tipoConsulta == 2){
        eObste.setAu(Integer.parseInt(this.txtfAlturaUterina.getText()));
        eObste.setImc(Float.parseFloat(this.lblIMC.getText()));
        eObste.setLcf(Integer.parseInt(this.txtfLCF.getText()));
        if(rbtnMafNo.isSelected())
            eObste.setMaf(false);
        else
            eObste.setMaf(true);
        eObste.setObservaciones(this.txtaObstetObservaciones.getText());
        eObste.setPa(Integer.parseInt(this.txtfPresionArterial.getText()));
        eObste.setPeso(Integer.parseInt(this.txtfPeso.getText()));
        eObste.setTalla(Float.parseFloat(this.txtfTalla.getText()));
    }
    }
    
    /**
     * Metodo utilizado para setear el estado de las cajas (Habilitado, Deshabilitado)
     * @param   accion true (Habilitado), false (Deshabilitado)
     * @param tipoConsulta tipo de consulta (0 Obstetrica , 1 Ginecologica y 2 Completa)
     */
    private void setearEstadoCajas(boolean accion, int tipoConsulta) {
        this.txtaMotivo.setEnabled(accion);
        this.txtaTratamiento.setEnabled(accion);
        this.txtaEstudiosComple.setEnabled(accion);
        this.txtaObservaciones.setEnabled(accion);
        this.txtfDiagnostico.setEnabled(accion);
        this.btnCancelar1.setEnabled(accion);
        if(tipoConsulta == 1 || tipoConsulta == 2)
        {
            this.txtaMamas.setEnabled(accion);
            this.txtaGenitoUrinario.setEnabled(accion);
            this.cmbBethesda.setEnabled(accion);
            this.txtaPapYColpo.setEnabled(accion);
        }
        if(tipoConsulta == 0 || tipoConsulta == 2)
        {
            this.txtfTalla.setEnabled(accion);
            this.txtfPeso.setEnabled(accion);
            this.txtfAlturaUterina.setEnabled(accion);
            this.txtfPresionArterial.setEnabled(accion);
            this.txtfLCF.setEnabled(accion);
            this.rbtnMafNo.setEnabled(accion);
            this.rbtnMafSi.setEnabled(accion);
            this.txtaObstetObservaciones.setEnabled(accion);
        }
        
    }
    
    /**
     * Metodo utilizado para invertir el estado de los botones (Habilitado, Deshabilitado)
     * @param   accion true (Habilitado), false (Deshabilitado)
     */
    private void cambiarBotones(boolean accion) {
        this.btnGuardar.setEnabled(accion);
        this.btnModificar.setEnabled(!accion);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/sistema.png"));
        return retValue;
    }
    }

