/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABMObrasSociales.java
 *
 * Created on 14-ago-2012, 17:36:11
 */
package GUI;

import ClasesBase.MensajesValidaciones;
import ClasesBase.ObraSocial;
import DAO.DAOObraSocial;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

public class ABMObrasSociales extends javax.swing.JFrame {

    private Frame padre;
    private DAOObraSocial daoObraSocial;
    private LinkedList<ObraSocial> obras;
    private DefaultTableModel dtmObras;
    private boolean esModificar;
    
    /** Creates new form ABMObrasSociales */
    public ABMObrasSociales(Frame parent) {
        initComponents();
        daoObraSocial = new DAOObraSocial();
        obras = daoObraSocial.getAllObrasSociales();
        llenarObrasSociales(obras);
        padre = (Principal) parent;
        this.setLocationRelativeTo(parent);
        esModificar = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlObraSociales = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblObrasSociales = new javax.swing.JTable();
        pnlBotonesABMObras = new javax.swing.JPanel();
        lblModificarObraSocial = new javax.swing.JLabel();
        lblEliminarObraSocial = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNombreObraSocial = new javax.swing.JTextField();
        lblNuevaObraSocial = new javax.swing.JLabel();
        lblVolverPrincipal = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Obras Sociales");
        setIconImage(getIconImage());
        setName("frmObrasSociales"); // NOI18N
        setResizable(false);

        pnlObraSociales.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlObraSociales.setName("pnlObrasSociales"); // NOI18N

        jScrollPane2.setFocusable(false);

        tblObrasSociales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Obras Sociales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblObrasSociales);

        javax.swing.GroupLayout pnlObraSocialesLayout = new javax.swing.GroupLayout(pnlObraSociales);
        pnlObraSociales.setLayout(pnlObraSocialesLayout);
        pnlObraSocialesLayout.setHorizontalGroup(
            pnlObraSocialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObraSocialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlObraSocialesLayout.setVerticalGroup(
            pnlObraSocialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObraSocialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBotonesABMObras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBotonesABMObras.setName("pnlBotonesABMObras"); // NOI18N

        lblModificarObraSocial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModificarObraSocial.setForeground(new java.awt.Color(0, 51, 102));
        lblModificarObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificarObraSocial.setText("Modificar Obra Social");
        lblModificarObraSocial.setToolTipText("");
        lblModificarObraSocial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblModificarObraSocial.setEnabled(false);
        lblModificarObraSocial.setName("lblModificarObraSocial"); // NOI18N
        lblModificarObraSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarObraSocialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModificarObraSocialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModificarObraSocialMouseExited(evt);
            }
        });

        lblEliminarObraSocial.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblEliminarObraSocial.setForeground(new java.awt.Color(0, 51, 102));
        lblEliminarObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarObraSocial.setText("Eliminar Obra Social");
        lblEliminarObraSocial.setToolTipText("");
        lblEliminarObraSocial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblEliminarObraSocial.setEnabled(false);
        lblEliminarObraSocial.setName("lblModificarObraSocial"); // NOI18N
        lblEliminarObraSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarObraSocialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarObraSocialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminarObraSocialMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesABMObrasLayout = new javax.swing.GroupLayout(pnlBotonesABMObras);
        pnlBotonesABMObras.setLayout(pnlBotonesABMObrasLayout);
        pnlBotonesABMObrasLayout.setHorizontalGroup(
            pnlBotonesABMObrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModificarObraSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
            .addComponent(lblEliminarObraSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        pnlBotonesABMObrasLayout.setVerticalGroup(
            pnlBotonesABMObrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesABMObrasLayout.createSequentialGroup()
                .addComponent(lblModificarObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lblEliminarObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Obra Social"));

        txtNombreObraSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreObraSocialKeyReleased(evt);
            }
        });

        lblNuevaObraSocial.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblNuevaObraSocial.setForeground(new java.awt.Color(0, 51, 102));
        lblNuevaObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNuevaObraSocial.setText("Guardar");
        lblNuevaObraSocial.setToolTipText("");
        lblNuevaObraSocial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNuevaObraSocial.setName("lblModificarObraSocial"); // NOI18N
        lblNuevaObraSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevaObraSocialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNuevaObraSocialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNuevaObraSocialMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreObraSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNuevaObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevaObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblVolverPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblVolverPrincipal.setForeground(new java.awt.Color(0, 51, 102));
        lblVolverPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolverPrincipal.setText("Volver a Principal");
        lblVolverPrincipal.setToolTipText("");
        lblVolverPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblVolverPrincipal.setName("lblModificarObraSocial"); // NOI18N
        lblVolverPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolverPrincipalMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVolverPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotonesABMObras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlObraSociales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(pnlObraSociales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBotonesABMObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(lblVolverPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void lblVolverPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverPrincipalMouseClicked
    this.dispose();
    padre.setVisible(true);
}//GEN-LAST:event_lblVolverPrincipalMouseClicked

private void lblNuevaObraSocialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevaObraSocialMouseClicked
    if (this.txtNombreObraSocial.getText().isEmpty()) {
        MensajesValidaciones.mostrarError(this, "Ingrese un nombre de obra social válido...");
        return;
    }
    if(!esModificar){
        if (daoObraSocial.registrarObraSocial(new ObraSocial(0, txtNombreObraSocial.getText()))) {
            MensajesValidaciones.mostrarInformacion(this, "Registro Exitoso.");
            this.txtNombreObraSocial.setText("");
            this.obras.removeAll(obras);
            this.obras = daoObraSocial.getAllObrasSociales();
            llenarObrasSociales(obras);
        } else {
            MensajesValidaciones.mostrarError(this, "Registro Fallido.");
        }
    }
    else
    {
        int idObraSeleccionada = obras.get(tblObrasSociales.getSelectedRow()).getId();
        if(daoObraSocial.modificarObraSocial(new ObraSocial(idObraSeleccionada,txtNombreObraSocial.getText())))
        {
        MensajesValidaciones.mostrarInformacion(this, "Actualización Exitosa.");
            this.txtNombreObraSocial.setText("");
            this.obras.removeAll(obras);
            this.obras = daoObraSocial.getAllObrasSociales();
            llenarObrasSociales(obras);
        } else {
            MensajesValidaciones.mostrarError(this, "Actualización Fallida.");
        }
    }
}//GEN-LAST:event_lblNuevaObraSocialMouseClicked

private void lblNuevaObraSocialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevaObraSocialMouseEntered
    this.setearLabels(lblNuevaObraSocial, true);
}//GEN-LAST:event_lblNuevaObraSocialMouseEntered

private void lblNuevaObraSocialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevaObraSocialMouseExited
    this.setearLabels(lblNuevaObraSocial, false);
}//GEN-LAST:event_lblNuevaObraSocialMouseExited

private void lblModificarObraSocialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarObraSocialMouseEntered
    this.setearLabels(lblModificarObraSocial, true);
}//GEN-LAST:event_lblModificarObraSocialMouseEntered

private void lblModificarObraSocialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarObraSocialMouseExited
    this.setearLabels(lblModificarObraSocial, false);
}//GEN-LAST:event_lblModificarObraSocialMouseExited

private void lblEliminarObraSocialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarObraSocialMouseEntered
    this.setearLabels(lblEliminarObraSocial, true);
}//GEN-LAST:event_lblEliminarObraSocialMouseEntered

private void lblEliminarObraSocialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarObraSocialMouseExited
    this.setearLabels(lblEliminarObraSocial, false);
}//GEN-LAST:event_lblEliminarObraSocialMouseExited

private void lblVolverPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverPrincipalMouseEntered
    this.setearLabels(lblVolverPrincipal, true);
}//GEN-LAST:event_lblVolverPrincipalMouseEntered

private void lblVolverPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverPrincipalMouseExited
    this.setearLabels(lblVolverPrincipal, false);
}//GEN-LAST:event_lblVolverPrincipalMouseExited

private void lblEliminarObraSocialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarObraSocialMouseClicked
    int idObraSeleccionada = obras.get(tblObrasSociales.getSelectedRow()).getId();
    if(daoObraSocial.eliminarObraSocial(new ObraSocial(idObraSeleccionada, ""))){
        MensajesValidaciones.mostrarInformacion(this, "Borrado Exitoso.");
        obras = daoObraSocial.getAllObrasSociales();
        llenarObrasSociales(obras);
    }
    else
        MensajesValidaciones.mostrarInformacion(this, "Borrado Fallido.");
}//GEN-LAST:event_lblEliminarObraSocialMouseClicked

private void txtNombreObraSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreObraSocialKeyReleased
    if(this.txtNombreObraSocial.getText().isEmpty())
        this.lblNuevaObraSocial.setEnabled(false);
    else
        this.lblNuevaObraSocial.setEnabled(true);
}//GEN-LAST:event_txtNombreObraSocialKeyReleased

private void lblModificarObraSocialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarObraSocialMouseClicked
    this.lblEliminarObraSocial.setFont(new java.awt.Font("Tahoma", 1, 14));
    int idObraSeleccionada = obras.get(tblObrasSociales.getSelectedRow()).getId();
    ObraSocial aModificar = daoObraSocial.getObraSocial(idObraSeleccionada);
    txtNombreObraSocial.setText(aModificar.getNombre());
    txtNombreObraSocial.grabFocus();
    esModificar = true;
}//GEN-LAST:event_lblModificarObraSocialMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEliminarObraSocial;
    private javax.swing.JLabel lblModificarObraSocial;
    private javax.swing.JLabel lblNuevaObraSocial;
    private javax.swing.JLabel lblVolverPrincipal;
    private javax.swing.JPanel pnlBotonesABMObras;
    private javax.swing.JPanel pnlObraSociales;
    private javax.swing.JTable tblObrasSociales;
    private javax.swing.JTextField txtNombreObraSocial;
    // End of variables declaration//GEN-END:variables

    private void llenarObrasSociales(LinkedList<ObraSocial> obras) {
        Object[] o;
        this.dtmObras = (DefaultTableModel) this.tblObrasSociales.getModel();
        this.borrarFilas(dtmObras);
        for (int i = 0; i < obras.size(); i++) {
            o = new Object[1];
            o[0] = obras.get(i).getNombre();
            dtmObras.addRow(o);
        }
        this.tblObrasSociales.changeSelection(0, 0, false, false);
    }
    private void borrarFilas(DefaultTableModel dtmObras) {
        int j = dtmObras.getRowCount();
        for (int i = 0; i < dtmObras.getRowCount();) {
            dtmObras.removeRow(0);
        }
    }
    
    private void setearLabels(JLabel jlbl, boolean entrada){
    if(!obras.isEmpty() || (jlbl == this.lblVolverPrincipal || jlbl == this.lblNuevaObraSocial)){
        if (entrada) {
            jlbl.setEnabled(true);
            jlbl.setFont(new java.awt.Font("Tahoma", 1, 13));
            jlbl.setForeground(new java.awt.Color(0, 51, 102));
        }
        else {
            jlbl.setEnabled(false);
            jlbl.setFont(new java.awt.Font("Tahoma", 1, 12));
            jlbl.setForeground(new java.awt.Color(0, 0, 0));
        }
    }
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/sistema.png"));
        return retValue;
    }
}
