/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABMObrasSociales.java
 *
 * Created on 14-ago-2012, 17:36:11
 */
package GUI;

import ClasesBase.ObraSocial;
import DAO.DAOObraSocial;
import java.awt.Frame;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Denise
 */
public class ABMObrasSociales extends javax.swing.JFrame {

    private Frame padre;
    private DAOObraSocial daoObraSocial;
    private LinkedList<ObraSocial> obras;
    private DefaultTableModel dtmObras;
    
    /** Creates new form ABMObrasSociales */
    public ABMObrasSociales(Frame parent) {
        initComponents();
        daoObraSocial = new DAOObraSocial();
        obras = daoObraSocial.getAllObrasSociales();
        llenarObrasSociales();
        padre = (Principal) parent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlObraSociales = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblObrasSociales = new javax.swing.JTable();
        pnlBotonesABMObras = new javax.swing.JPanel();
        lblModificarObraSocial = new javax.swing.JLabel();
        lblEliminarObraSocial = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNombreObraSocial = new javax.swing.JTextField();
        lblNuevaObraSocial = new javax.swing.JLabel();
        lblVolverPrincipal = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlObraSociales.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlObraSociales.setName("pnlObrasSociales"); // NOI18N

        jScrollPane2.setColumnHeader(null);
        jScrollPane2.setFocusable(false);

        tblObrasSociales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Obras Sociales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblObrasSociales);

        javax.swing.GroupLayout pnlObraSocialesLayout = new javax.swing.GroupLayout(pnlObraSociales);
        pnlObraSociales.setLayout(pnlObraSocialesLayout);
        pnlObraSocialesLayout.setHorizontalGroup(
            pnlObraSocialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObraSocialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlObraSocialesLayout.setVerticalGroup(
            pnlObraSocialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlObraSocialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBotonesABMObras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBotonesABMObras.setName("pnlBotonesABMObras"); // NOI18N

        lblModificarObraSocial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModificarObraSocial.setForeground(new java.awt.Color(0, 51, 102));
        lblModificarObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificarObraSocial.setText("Modificar Obra Social");
        lblModificarObraSocial.setToolTipText("");
        lblModificarObraSocial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblModificarObraSocial.setName("lblModificarObraSocial"); // NOI18N

        lblEliminarObraSocial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEliminarObraSocial.setForeground(new java.awt.Color(0, 51, 102));
        lblEliminarObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarObraSocial.setText("Eliminar Obra Social");
        lblEliminarObraSocial.setToolTipText("");
        lblEliminarObraSocial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblEliminarObraSocial.setName("lblModificarObraSocial"); // NOI18N

        javax.swing.GroupLayout pnlBotonesABMObrasLayout = new javax.swing.GroupLayout(pnlBotonesABMObras);
        pnlBotonesABMObras.setLayout(pnlBotonesABMObrasLayout);
        pnlBotonesABMObrasLayout.setHorizontalGroup(
            pnlBotonesABMObrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModificarObraSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(lblEliminarObraSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );
        pnlBotonesABMObrasLayout.setVerticalGroup(
            pnlBotonesABMObrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesABMObrasLayout.createSequentialGroup()
                .addComponent(lblModificarObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lblEliminarObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Obra Social"));

        lblNuevaObraSocial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNuevaObraSocial.setForeground(new java.awt.Color(0, 51, 102));
        lblNuevaObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNuevaObraSocial.setText("Guardar");
        lblNuevaObraSocial.setToolTipText("");
        lblNuevaObraSocial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNuevaObraSocial.setName("lblModificarObraSocial"); // NOI18N
        lblNuevaObraSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevaObraSocialMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreObraSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNuevaObraSocial)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevaObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblVolverPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblVolverPrincipal.setForeground(new java.awt.Color(0, 51, 102));
        lblVolverPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolverPrincipal.setText("Volver a Ventana Principal");
        lblVolverPrincipal.setToolTipText("");
        lblVolverPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblVolverPrincipal.setName("lblModificarObraSocial"); // NOI18N
        lblVolverPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverPrincipalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotonesABMObras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVolverPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlObraSociales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlObraSociales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBotonesABMObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVolverPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void lblVolverPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverPrincipalMouseClicked
    padre.setVisible(true);
    this.dispose();
}//GEN-LAST:event_lblVolverPrincipalMouseClicked

private void lblNuevaObraSocialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevaObraSocialMouseClicked

}//GEN-LAST:event_lblNuevaObraSocialMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEliminarObraSocial;
    private javax.swing.JLabel lblModificarObraSocial;
    private javax.swing.JTextField lblNombreObraSocial;
    private javax.swing.JLabel lblNuevaObraSocial;
    private javax.swing.JLabel lblVolverPrincipal;
    private javax.swing.JPanel pnlBotonesABMObras;
    private javax.swing.JPanel pnlObraSociales;
    private javax.swing.JTable tblObrasSociales;
    // End of variables declaration//GEN-END:variables

    private void llenarObrasSociales() {
        Object[] o;
        this.dtmObras = (DefaultTableModel) this.tblObrasSociales.getModel();
        this.borrarFilas(dtmObras);
        for (int i = 0; i < obras.size(); i++) {
            o = new Object[1];
            o[0] = obras.get(i).getNombre();
            dtmObras.addRow(o);
        }
        this.tblObrasSociales.changeSelection(0, 0, false, false);
    }
    private void borrarFilas(DefaultTableModel dtmObras) {
        int j = dtmObras.getRowCount();
        for (int i = 0; i < dtmObras.getRowCount();) {
            dtmObras.removeRow(0);
        }
    }
}
