/*
 * EleccionColor.java
 *
 * Created on 07-oct-2012, 15:38:54
 */
package GUI;

import ClasesBase.GestorEstilos;
import ClasesBase.ThreadFiles;

/**
 *
 * @author Denise
 */
public class EleccionColor extends javax.swing.JDialog {

    public Principal padre;
    private int color = GestorEstilos.colorActual;
    private ThreadFiles thread;
    
    /** Creates new form EleccionColor */
    public EleccionColor(Principal parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.padre = parent;
        this.setLocationRelativeTo(parent);
        GestorEstilos.pintar(this);
        thread = new ThreadFiles(this);
        thread.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbtn4 = new javax.swing.JRadioButton();
        rbtn5 = new javax.swing.JRadioButton();
        rbtn6 = new javax.swing.JRadioButton();
        rbtn1 = new javax.swing.JRadioButton();
        rbtn2 = new javax.swing.JRadioButton();
        rbtn3 = new javax.swing.JRadioButton();
        btnAplicar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        rbtn0 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Color de Fondo");
        setResizable(false);

        rbtn4.setBackground(new java.awt.Color(255, 252, 204));
        buttonGroup1.add(rbtn4);
        rbtn4.setFont(new java.awt.Font("Tahoma", 0, 14));
        rbtn4.setText("Amarillo");

        rbtn5.setBackground(new java.awt.Color(225, 225, 254));
        buttonGroup1.add(rbtn5);
        rbtn5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn5.setText("Azul");

        rbtn6.setBackground(new java.awt.Color(232, 179, 245));
        buttonGroup1.add(rbtn6);
        rbtn6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn6.setText("Lila");
        rbtn6.setMaximumSize(new java.awt.Dimension(45, 23));
        rbtn6.setMinimumSize(new java.awt.Dimension(45, 23));
        rbtn6.setPreferredSize(new java.awt.Dimension(45, 23));

        rbtn1.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(rbtn1);
        rbtn1.setFont(new java.awt.Font("Tahoma", 0, 14));
        rbtn1.setText("Rosa Pálido");

        rbtn2.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(rbtn2);
        rbtn2.setFont(new java.awt.Font("Tahoma", 0, 14));
        rbtn2.setText("Rosa Viejo");

        rbtn3.setBackground(new java.awt.Color(179, 225, 194));
        buttonGroup1.add(rbtn3);
        rbtn3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn3.setText("Verde");

        btnAplicar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAplicar.setText("Aplicar");
        btnAplicar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAplicar.setContentAreaFilled(false);
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Listo");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn0);
        rbtn0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn0.setText("Color por defecto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn0, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAplicar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(rbtn3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(rbtn2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(rbtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(rbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(rbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn0, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
    if(rbtn0.isSelected())
        color = 0;
    if(rbtn1.isSelected())
        color = 1;
    if(rbtn2.isSelected())
        color = 2;
    if(rbtn3.isSelected())
        color = 3;
    if(rbtn4.isSelected())
        color = 4;
    if(rbtn5.isSelected())
        color = 5;
    if(rbtn6.isSelected())
        color = 6;
    thread.put(color);
}//GEN-LAST:event_btnAplicarActionPerformed

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rbtn0;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JRadioButton rbtn3;
    private javax.swing.JRadioButton rbtn4;
    private javax.swing.JRadioButton rbtn5;
    private javax.swing.JRadioButton rbtn6;
    // End of variables declaration//GEN-END:variables

}
