/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Fran
 */
public class ABMConsultaObstetrica extends javax.swing.JDialog {

    /**
     * Creates new form ABMConsultaObstetrica
     */
    public ABMConsultaObstetrica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpMAF = new javax.swing.ButtonGroup();
        lblstaticTratamiento = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        txtfDiagnostico = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtaObservaciones = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtaTratamiento = new javax.swing.JTextArea();
        lblstaticFecha = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtaEstudiosComple = new javax.swing.JTextArea();
        lblstaticDiagnostico = new javax.swing.JLabel();
        btnVolverHC = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtaMotivo = new javax.swing.JTextArea();
        lblFecha = new javax.swing.JLabel();
        lblstaticEstudiosComple = new javax.swing.JLabel();
        lblstaticConsObserv = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lblstaticMotivo = new javax.swing.JLabel();
        pnlObstetrico = new javax.swing.JPanel();
        rbtnMafNo = new javax.swing.JRadioButton();
        rbtnMafSi = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaObstetObservaciones = new javax.swing.JTextArea();
        lblstaticObstetricoObserv = new javax.swing.JLabel();
        lblstaticAU = new javax.swing.JLabel();
        lblstaticTalla = new javax.swing.JLabel();
        lblstaticPeso = new javax.swing.JLabel();
        lblstaticLCF = new javax.swing.JLabel();
        lblstaticMAF = new javax.swing.JLabel();
        txtfLCF = new javax.swing.JTextField();
        txtfPeso = new javax.swing.JTextField();
        txtfTalla = new javax.swing.JTextField();
        lblstaticPA = new javax.swing.JLabel();
        txtfPresionArterial = new javax.swing.JTextField();
        txtfAlturaUterina = new javax.swing.JTextField();
        lblstaticUnidadPA = new javax.swing.JLabel();
        lblstaticUnidadAU = new javax.swing.JLabel();
        lblstaticUnidadTalla = new javax.swing.JLabel();
        lblstaticUnidadPeso = new javax.swing.JLabel();
        lblstaticUnidadLCF = new javax.swing.JLabel();
        lblstaticIMC = new javax.swing.JLabel();
        lblIMC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblstaticTratamiento.setText("Tratamiento:");

        btnSalir.setText("Salir");

        txtaObservaciones.setColumns(20);
        txtaObservaciones.setLineWrap(true);
        txtaObservaciones.setRows(2);
        jScrollPane8.setViewportView(txtaObservaciones);

        txtaTratamiento.setColumns(20);
        txtaTratamiento.setLineWrap(true);
        txtaTratamiento.setRows(2);
        jScrollPane7.setViewportView(txtaTratamiento);

        lblstaticFecha.setText("Fecha:");

        txtaEstudiosComple.setColumns(20);
        txtaEstudiosComple.setLineWrap(true);
        txtaEstudiosComple.setRows(2);
        jScrollPane10.setViewportView(txtaEstudiosComple);

        lblstaticDiagnostico.setText("Diagnostico:");

        btnVolverHC.setText("Volver a la HC");
        btnVolverHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverHCActionPerformed(evt);
            }
        });

        txtaMotivo.setColumns(20);
        txtaMotivo.setLineWrap(true);
        txtaMotivo.setRows(2);
        jScrollPane9.setViewportView(txtaMotivo);

        lblFecha.setText("FechaDeHoy");

        lblstaticEstudiosComple.setText("Estudios Complementarios:");

        lblstaticConsObserv.setText("Observaciones:");

        btnGuardar.setText("Guardar");

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);

        lblstaticMotivo.setText("Motivo:");

        pnlObstetrico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Examenes"));

        btngrpMAF.add(rbtnMafNo);
        rbtnMafNo.setText("NO");

        btngrpMAF.add(rbtnMafSi);
        rbtnMafSi.setText("SI");

        txtaObstetObservaciones.setColumns(20);
        txtaObstetObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtaObstetObservaciones);

        lblstaticObstetricoObserv.setText("Observaciones:");

        lblstaticAU.setText("Altura Uterina:");

        lblstaticTalla.setText("Talla:");

        lblstaticPeso.setText("Peso:");

        lblstaticLCF.setText("LCF:");

        lblstaticMAF.setText("MAF:");

        lblstaticPA.setText("Presion Arterial:");

        lblstaticUnidadPA.setText("mm/hg");

        lblstaticUnidadAU.setText("cm");

        lblstaticUnidadTalla.setText("cm");

        lblstaticUnidadPeso.setText("Kg");

        lblstaticUnidadLCF.setText("lpm");

        lblstaticIMC.setText("IMC:");

        lblIMC.setText("Aca va el imc");

        javax.swing.GroupLayout pnlObstetricoLayout = new javax.swing.GroupLayout(pnlObstetrico);
        pnlObstetrico.setLayout(pnlObstetricoLayout);
        pnlObstetricoLayout.setHorizontalGroup(
            pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObstetricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlObstetricoLayout.createSequentialGroup()
                        .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblstaticTalla)
                            .addComponent(lblstaticPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblstaticIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtfTalla, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfPeso)
                            .addComponent(lblIMC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstaticUnidadTalla)
                            .addComponent(lblstaticUnidadPeso))
                        .addGap(32, 32, 32)
                        .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlObstetricoLayout.createSequentialGroup()
                                .addComponent(lblstaticAU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfAlturaUterina, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlObstetricoLayout.createSequentialGroup()
                                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblstaticPA)
                                    .addComponent(lblstaticMAF)
                                    .addComponent(lblstaticLCF))
                                .addGap(18, 18, 18)
                                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfPresionArterial)
                                    .addComponent(txtfLCF)
                                    .addGroup(pnlObstetricoLayout.createSequentialGroup()
                                        .addComponent(rbtnMafSi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnMafNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstaticUnidadPA)
                            .addComponent(lblstaticUnidadAU)
                            .addComponent(lblstaticUnidadLCF)))
                    .addComponent(lblstaticObstetricoObserv)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlObstetricoLayout.setVerticalGroup(
            pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObstetricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaticTalla)
                    .addComponent(txtfTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticAU)
                    .addComponent(txtfAlturaUterina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticUnidadAU)
                    .addComponent(lblstaticUnidadTalla))
                .addGap(18, 18, 18)
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaticPeso)
                    .addComponent(txtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticPA)
                    .addComponent(txtfPresionArterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticUnidadPA)
                    .addComponent(lblstaticUnidadPeso))
                .addGap(21, 21, 21)
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaticLCF)
                    .addComponent(txtfLCF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstaticUnidadLCF)
                    .addComponent(lblstaticIMC)
                    .addComponent(lblIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlObstetricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMafSi)
                    .addComponent(rbtnMafNo)
                    .addComponent(lblstaticMAF))
                .addGap(18, 18, 18)
                .addComponent(lblstaticObstetricoObserv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblstaticFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnGuardar)
                            .addGap(18, 18, 18)
                            .addComponent(btnModificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVolverHC)
                            .addGap(18, 18, 18)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblstaticMotivo)
                                .addComponent(lblstaticTratamiento)
                                .addComponent(lblstaticEstudiosComple)
                                .addComponent(lblstaticDiagnostico)
                                .addComponent(lblstaticConsObserv)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtfDiagnostico, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9)))
                            .addGap(18, 18, 18)
                            .addComponent(pnlObstetrico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstaticFecha)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblstaticMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lblstaticTratamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblstaticEstudiosComple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lblstaticConsObserv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lblstaticDiagnostico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlObstetrico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnVolverHC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverHCActionPerformed
        this.dispose();
//        HC.setVisible(true);
    }//GEN-LAST:event_btnVolverHCActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolverHC;
    private javax.swing.ButtonGroup btngrpMAF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblstaticAU;
    private javax.swing.JLabel lblstaticConsObserv;
    private javax.swing.JLabel lblstaticDiagnostico;
    private javax.swing.JLabel lblstaticEstudiosComple;
    private javax.swing.JLabel lblstaticFecha;
    private javax.swing.JLabel lblstaticIMC;
    private javax.swing.JLabel lblstaticLCF;
    private javax.swing.JLabel lblstaticMAF;
    private javax.swing.JLabel lblstaticMotivo;
    private javax.swing.JLabel lblstaticObstetricoObserv;
    private javax.swing.JLabel lblstaticPA;
    private javax.swing.JLabel lblstaticPeso;
    private javax.swing.JLabel lblstaticTalla;
    private javax.swing.JLabel lblstaticTratamiento;
    private javax.swing.JLabel lblstaticUnidadAU;
    private javax.swing.JLabel lblstaticUnidadLCF;
    private javax.swing.JLabel lblstaticUnidadPA;
    private javax.swing.JLabel lblstaticUnidadPeso;
    private javax.swing.JLabel lblstaticUnidadTalla;
    private javax.swing.JPanel pnlObstetrico;
    private javax.swing.JRadioButton rbtnMafNo;
    private javax.swing.JRadioButton rbtnMafSi;
    private javax.swing.JTextArea txtaEstudiosComple;
    private javax.swing.JTextArea txtaMotivo;
    private javax.swing.JTextArea txtaObservaciones;
    private javax.swing.JTextArea txtaObstetObservaciones;
    private javax.swing.JTextArea txtaTratamiento;
    private javax.swing.JTextField txtfAlturaUterina;
    private javax.swing.JTextField txtfDiagnostico;
    private javax.swing.JTextField txtfLCF;
    private javax.swing.JTextField txtfPeso;
    private javax.swing.JTextField txtfPresionArterial;
    private javax.swing.JTextField txtfTalla;
    // End of variables declaration//GEN-END:variables
}
